# Generated by Django 3.2.5 on 2022-06-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['article']},
        ),
    ]
