# Generated by Django 3.2.5 on 2022-06-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_id', models.CharField(blank=True, max_length=52, null=True)),
                ('costumer_username', models.CharField(blank=True, max_length=52, null=True)),
                ('first_name', models.CharField(blank=True, max_length=52, null=True)),
                ('last_name', models.CharField(blank=True, max_length=52, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('country_code', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=52, null=True)),
                ('city', models.CharField(blank=True, max_length=52, null=True)),
                ('street_line1', models.CharField(blank=True, max_length=52, null=True)),
                ('street_line2', models.CharField(blank=True, max_length=52, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product')),
            ],
        ),
    ]
