# Generated by Django 3.2.5 on 2022-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220609_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider_payment_charge_id',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
