# Generated by Django 3.2.5 on 2022-06-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220610_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-modified_at']},
        ),
    ]
