# Generated by Django 3.2.5 on 2022-06-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payload',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
